[bot]
owner_tg_id = "BOT_OWNER_TG_ID"
token = "BOT_TOKEN"
drop_pending = "BOT_DROP_PENDING"
use_webhook = "BOT_USE_WEBHOOK"
use_class_middlewares = "BOT_USE_CLASS_MIDDLEWARES"
actions_timeout = "BOT_ACTIONS_TIMEOUT"
page_size = "BOT_PAGE_SIZE"

logger.name = "BOT_LOGGER_NAME"
logger.level = "BOT_LOGGER_LEVEL"
logger.stream = "BOT_LOGGER_STREAM"
logger.file_path = "BOT_LOGGER_FILE_PATH"
logger.format = "BOT_LOGGER_FORMAT"

allowed_updates = "BOT_ALLOWED_UPDATES"

state_storage.type = "BOT_STATE_STORAGE_TYPE"
state_storage.redis.host = "BOT_STATE_STORAGE_REDIS_HOST"
state_storage.redis.port = "BOT_STATE_STORAGE_REDIS_PORT"
state_storage.redis.db = "BOT_STATE_STORAGE_REDIS_DB"
state_storage.redis.password = "BOT_STATE_STORAGE_REDIS_PASSWORD"
state_storage.redis.prefix = "BOT_STATE_STORAGE_REDIS_PREFIX"

webhook.url = "BOT_WEBHOOK_URL"
webhook.secret_token = "BOT_WEBHOOK_SECRET_TOKEN"
webhook.cert_path = "BOT_WEBHOOK_CERT_PATH"
webhook.ip_address = "BOT_WEBHOOK_IP_ADDRESS"
webhook.max_connections = "BOT_WEBHOOK_MAX_CONNECTIONS"

telegram_api_url = "BOT_TELEGRAM_API_URL"

[db]
host = "DB_HOST"
port = "DB_PORT"
user = "DB_USER"
password = "DB_PASSWORD"
database = "DB_DATABASE"

logger.name = "DB_LOGGER_NAME"
logger.level = "DB_LOGGER_LEVEL"
logger.stream = "DB_LOGGER_STREAM"
logger.file_path = "DB_LOGGER_FILE_PATH"
logger.format = "DB_LOGGER_FORMAT"

# [extra sections if any]
# ...

[logger]
name = "LOGGER_NAME"
level = "LOGGER_LEVEL"
stream = "LOGGER_STREAM"
file_path = "LOGGER_FILE_PATH"
format = "LOGGER_FORMAT"

[messages]
welcome = "MESSAGES_WELCOME"
unregistered_help = "MESSAGES_UNREGISTERED_HELP"
player_help = "MESSAGES_PLAYER_HELP"
manager_help = "MESSAGES_MANAGER_HELP"
owner_help = "MESSAGES_OWNER_HELP"
anti_flood = "MESSAGES_ANTI_FLOOD"
get_player_name = "MESSAGES_GET_PLAYER_NAME"
invalid_player_name = "MESSAGES_INVALID_PLAYER_NAME"
player_name_already_taken = "MESSAGES_PLAYER_NAME_ALREADY_TAKEN"
player_registered = "MESSAGES_PLAYER_REGISTERED"
player_balance = "MESSAGES_PLAYER_BALANCE"
choose_money_transfer_recipient = "MESSAGES_CHOOSE_MONEY_TRANSFER_RECIPIENT"
money_transfer_recipient_cancelled = "MESSAGES_MONEY_TRANSFER_RECIPIENT_CANCELLED"
choose_money_transfer_amount = "MESSAGES_CHOOSE_MONEY_TRANSFER_AMOUNT"
money_transfer_success = "MESSAGES_MONEY_TRANSFER_SUCCESS"
choose_new_queue_location = "MESSAGES_CHOOSE_NEW_QUEUE_LOCATION"
new_queue_location_cancelled = "MESSAGES_NEW_QUEUE_LOCATION_CANCELLED"
queue_entry_added = "MESSAGES_QUEUE_ENTRY_ADDED"
player_queue_location = "MESSAGES_PLAYER_QUEUE_LOCATION"
player_left_queue = "MESSAGES_PLAYER_LEFT_QUEUE"
manager_registration_forbidden = "MESSAGES_MANAGER_REGISTRATION_FORBIDDEN"
manager_registration_disabled = "MESSAGES_MANAGER_REGISTRATION_DISABLED"
get_manager_password = "MESSAGES_GET_MANAGER_PASSWORD"
get_manager_name = "MESSAGES_GET_MANAGER_NAME"
invalid_manager_name = "MESSAGES_INVALID_MANAGER_NAME"
manager_name_already_taken = "MESSAGES_MANAGER_NAME_ALREADY_TAKEN"
manager_registered = "MESSAGES_MANAGER_REGISTERED"
all_players = "MESSAGES_ALL_PLAYERS"
all_players_cancelled = "MESSAGES_ALL_PLAYERS_CANCELLED"
all_locations = "MESSAGES_ALL_LOCATIONS"
all_locations_cancelled = "MESSAGES_ALL_LOCATIONS_CANCELLED"
choose_add_balance_recipient = "MESSAGES_CHOOSE_ADD_BALANCE_RECIPIENT"
add_balance_cancelled = "MESSAGES_ADD_BALANCE_CANCELLED"
choose_add_balance_amount = "MESSAGES_CHOOSE_ADD_BALANCE_AMOUNT"
choose_subtract_balance_recipient = "MESSAGES_CHOOSE_SUBTRACT_BALANCE_RECIPIENT"
subtract_balance_cancelled = "MESSAGES_SUBTRACT_BALANCE_CANCELLED"
choose_subtract_balance_amount = "MESSAGES_CHOOSE_SUBTRACT_BALANCE_AMOUNT"
choose_reward_recipient = "MESSAGES_CHOOSE_REWARD_RECIPIENT"
reward_cancelled = "MESSAGES_REWARD_CANCELLED"
choose_reward_amount = "MESSAGES_CHOOSE_REWARD_AMOUNT"
reward_successful = "MESSAGES_REWARD_SUCCESSFUL"
choose_purchase_recipient = "MESSAGES_CHOOSE_PURCHASE_RECIPIENT"
purchase_cancelled = "MESSAGES_PURCHASE_CANCELLED"
choose_purchase_amount = "MESSAGES_CHOOSE_PURCHASE_AMOUNT"
purchase_successful = "MESSAGES_PURCHASE_SUCCESSFUL"
choose_location = "MESSAGES_CHOOSE_LOCATION"
choose_location_cancelled = "MESSAGES_CHOOSE_LOCATION_CANCELLED"
location_updated = "MESSAGES_LOCATION_UPDATED"
chosen_location = "MESSAGES_CHOSEN_LOCATION"
my_location_queue = "MESSAGES_MY_LOCATION_QUEUE"
my_location_queue_cancelled = "MESSAGES_MY_LOCATION_QUEUE_CANCELLED"
location_player_chosen_options = "MESSAGES_LOCATION_PLAYER_CHOSEN_OPTIONS"
location_paused = "MESSAGES_LOCATION_PAUSED"
location_unpaused = "MESSAGES_LOCATION_UNPAUSED"
manager_my_location = "MESSAGES_MANAGER_MY_LOCATION"
manager_left_location = "MESSAGES_MANAGER_LEFT_LOCATION"
manager_password_set = "MESSAGES_MANAGER_PASSWORD_SET"
manager_password_reset = "MESSAGES_MANAGER_PASSWORD_RESET"
location_added = "MESSAGES_LOCATION_ADDED"
invalid_add_location_args = "MESSAGES_INVALID_ADD_LOCATION_ARGS"
add_player_error = "MESSAGES_ADD_PLAYER_ERROR"
player_not_found_error = "MESSAGES_PLAYER_NOT_FOUND_ERROR"
player_not_in_queue_error = "MESSAGES_PLAYER_NOT_IN_QUEUE_ERROR"
queue_entry_already_exists_error = "MESSAGES_QUEUE_ENTRY_ALREADY_EXISTS_ERROR"
money_transfer_recipient_not_chosen_error = "MESSAGES_MONEY_TRANSFER_RECIPIENT_NOT_CHOSEN_ERROR"
money_transfer_amount_invalid_error = "MESSAGES_MONEY_TRANSFER_AMOUNT_INVALID_ERROR"
add_manager_error = "MESSAGES_ADD_MANAGER_ERROR"
manager_not_on_location_error = "MESSAGES_MANAGER_NOT_ON_LOCATION_ERROR"
bad_location_error = "MESSAGES_BAD_LOCATION_ERROR"
pause_location_error = "MESSAGES_PAUSE_LOCATION_ERROR"
unpause_location_error = "MESSAGES_UNPAUSE_LOCATION_ERROR"
bad_player_balance_error = "MESSAGES_BAD_PLAYER_BALANCE_ERROR"
bad_chosen_player_error = "MESSAGES_BAD_CHOSEN_PLAYER_ERROR"
bad_manager_error = "MESSAGES_BAD_MANAGER_ERROR"
add_user_error = "MESSAGES_ADD_USER_ERROR"
add_tg_account_error = "MESSAGES_ADD_TG_ACCOUNT_ERROR"
unknown_error = "MESSAGES_UNKNOWN_ERROR"

[buttons]
reg_player = "BUTTONS_REG_PLAYER"
reg_manager = "BUTTONS_REG_MANAGER"
new_queue = "BUTTONS_NEW_QUEUE"
my_balance = "BUTTONS_MY_BALANCE"
transfer_money = "BUTTONS_TRANSFER_MONEY"
my_queue = "BUTTONS_MY_QUEUE"
leave_queue = "BUTTONS_LEAVE_QUEUE"
list_all_players = "BUTTONS_LIST_ALL_PLAYERS"
list_all_locations = "BUTTONS_LIST_ALL_LOCATIONS"
add_balance = "BUTTONS_ADD_BALANCE"
subtract_balance = "BUTTONS_SUBTRACT_BALANCE"
choose_location = "BUTTONS_CHOOSE_LOCATION"
reward_player = "BUTTONS_REWARD_PLAYER"
purchase = "BUTTONS_PURCHASE"
my_location = "BUTTONS_MY_LOCATION"
my_location_queue = "BUTTONS_MY_LOCATION_QUEUE"
leave_location = "BUTTONS_LEAVE_LOCATION"
pause_location = "BUTTONS_PAUSE_LOCATION"
unpause_location = "BUTTONS_UNPAUSE_LOCATION"
prev_page = "BUTTONS_PREV_PAGE"
next_page = "BUTTONS_NEXT_PAGE"
help = "BUTTONS_HELP"
cancel = "BUTTONS_CANCEL"
